### ISSUE TITLE
Matrix norms docs

### ISSUE THREAD

**Issue by Metaxal** [soegaard/sci#1]
First, excellent work on the documentation!

The docs' definition of ||A||_2 is actually the Frobenius norm ||A||_F (also the entrywise matrix 2-norm), not the matrix (operator) 2-norm. It is probably best to define ||A||_2 as in [WP](https://en.wikipedia.org/wiki/Matrix_norm#Special_cases). The Frobenius norm is still pretty useful to have in any case.

||A||_maxabs should be just ||A||_max, and it is indeed a [norm](https://en.wikipedia.org/wiki/Norm_(mathematics)) as far as I can tell.

**Comment by soegaard** [comment]
The text was wrong, so I changed it to say Frobenius norm everywhere
(which is what the code computes).

I removed the note on the max norm. I misread the LAPACK documentation:

>  Note that  max(abs(A(i,j)))  is not a consistent matrix norm.

**Comment by Metaxal** [comment]
Cool. I think you should also rename `'max-abs` to just `'max` in the code too, but I won't insist further if you'd rather not to for some reason.

**Comment by soegaard** [comment]
Missed those. Now fixed.

**Comment by Metaxal** [comment]
Excellent, thanks!
