### ISSUE TITLE
Matrices not being freed when garbage collected

### ISSUE THREAD

**Issue by massung** [soegaard/sci#10]
Simple test:

1. Start DrRacket
2. In the expression area evaluate:

```racket
(require flomat)
(zeros 10000 10000)
```

3. Observe ~700 MB of RAM is used (reported by DrRacket and whatever external RAM usage app your OS has)
4. Click "Run" to clean everything up
5. Observe RAM usage reported by DrRacket is back to initial levels
6. External monitor shows memory still being used

My guess is that BLAS (or whatever is being wrapped) has a `free_matrix` function that needs to be called. Racket now has methods for automatically freeing the memory when the object is "freed" by the GC. See an example usage with my CSFML package: https://github.com/massung/racket-csfml/blob/master/graphics.rkt#L73

**Comment by soegaard** [comment]
Hi,

Is this still an issue?

I tried this loop in the terminal (macOS):

```
% racket84
Welcome to Racket v8.4 [cs].
> (require flomat)
> (let loop () (zeros 10000 10000) (loop))
```

The looked at memory usage in Activity Monitor and everything looked normal.

All memory allocations are done with `malloc` in `atomic` mode, so memory ought to be reclaimed automatically.

**Comment by massung** [comment]
Sorry, I missed this somehow. It totally looks good to me as well. Thanks for following up. Closing the issue.
