### ISSUE TITLE
libgfortran on Debian

### ISSUE THREAD

**Issue by kengruven** [soegaard/sci#15]
I installed "sci" on Racket just now, and it fails to load:

```
; ffi-lib: could not load foreign library
;   path: libgfortran.so.3
;   system error: libgfortran.so.3: cannot open shared object file: No such
;     file or directory
```

Looking at flomat.rkt (which I found via issue #8), it looks like it's configured to use libgfortran 3 on Debian.  I'm using Debian stable, which has libgfortran 5.  (I don't know how old libgfortran 3 is, but probably pretty old -- Debian "buster" in 2019 had libgfortran 4.)

(Also, I'm not an Arch Linux user, but I searched on archlinux.org just now and the current gcc provides "libgfortran.so=5-64".  Maybe it's time to default to libgfortran 5.  Is anyone still shipping libgfortran 3?)

Thanks!

**Comment by soegaard** [comment]
@kengruven Thanks for the report.

For now I added a line to look for version 5 when using Debian.
I have alerted the package server at pkgs.racket-lang.org that there is an update.

Can you test that it works?

**Comment by kengruven** [comment]
I'd be happy to test it.  It looks like I have to wait for [the server](https://pkgs.racket-lang.org/package/sci) to respond to your update -- maybe on Sundays?

**Comment by soegaard** [comment]
I think, an `raco update sci` ought to fetch the latest version even if the server haven't caught up yet.
But sunday is fine.

**Comment by kengruven** [comment]
Even uninstalling and reinstalling it didn't help, before.  But the server has caught up, and today it works.  Thank you!
