### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by rohanposthumus** [soegaard/sci#4]
The documentation at "https://docs.racket-lang.org/manual-flomat/index.html#%28part._.Introduction%29" under "3. Installation"
states that you should use "raco pkg install flomat" but Github states "raco pkg install sci".
Would you mind updating the documentation for new users?

**Comment by soegaard** [comment]
Thanks for letting me know.
The docs are now uptodate.

Originally the package was named `flomat`, but then I got the idea
that `flomat` could of of several science related packages.
The `sci` package is thus meant to contain `flomat` and friends.
(But `flomat` is the only package yet.)

9e032e6232d3c262ca88f546d05ea250edfba80b
