### ISSUE TITLE
ffi-lib could not load libgfortran

### ISSUE THREAD

**Issue by lojic** [soegaard/sci#8]
I have a Raspberry Pi 2 Model B with the latest Raspberry Pi OS. Here is the output of `(system-type 'machine)`
```
Welcome to Racket v8.3 [cs].
> (system-type 'machine)
"Linux raspberrypi 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l"
```
Looking at the `flomat` source, it will not detect my computer properly.  Here's the libgfortran I installed:

`libgfortran5/stable,now 10.2.1-6+rpi1 armhf [installed]`

**Comment by samdphillips** [comment]
I am on Ubuntu 22.04 LTS and it seems that the oldest `libgfortran` is the same version that @lojic reported.

**Comment by soegaard** [comment]
@samdphillips 
It seems the docs no longer builds on the package [1] server due to:

> ffi-lib: could not load foreign library
>  path: libgfortran.so.5
>  system error: libgfortran.so.5: cannot open shared object file: No such file or directory


[1] https://pkg-build.racket-lang.org/server/built/fail/sci.txt

**Comment by soegaard** [comment]
I have added version 3 to the list of acceptable versions to try on Ubuntu.
Let's see if the package server npw builds the docs.

**Comment by soegaard** [comment]
It seems it worked.
